### ISSUE TITLE
fix changing drain status should only be possible when a drain is adopted

### ISSUE THREAD

**Issue by Mloweedgar** [Samweli/twaa-mtaro#133]
for example one can not set drain to clean status if no one has adopted that drain

**Comment by Samweli** [comment]
This is right, except it is a street leader who want to change the drain status.

**Comment by Mloweedgar** [comment]
Currently the sub-ward leader is able to update status of non-adopted drain and normal users are able to only update the status of their drain claim, therefore this issue can be closed
