### ISSUE TITLE
fix show claim list table when drain need help

### ISSUE THREAD

**Issue by Mloweedgar** [Samweli/twaa-mtaro#135]

**Comment by Samweli** [comment]
I think I have already fixed this in https://github.com/Samweli/twaa-mtaro/commit/a615e28b3710390fa9fcff43f112441c8ca9c561

**Comment by Mloweedgar** [comment]
closed in https://github.com/Mloweedgar/twaa-mtaro/commit/8d4801732b9c0137f8c5aceff25783708bbbac0d
