### ISSUE TITLE
Update column in all user list table

### ISSUE THREAD

**Issue by Samweli** [Samweli/twaa-mtaro#30]
Remove index column in assigning drain user list

**Comment by Mloweedgar** [comment]
I have already fixed this issue in https://github.com/Mloweedgar/twaa-mtaro/commit/0b8395ed7088313cd6fe2e7e74ca56340f194431

**Comment by Samweli** [comment]
This is closed, here https://github.com/Mloweedgar/twaa-mtaro/commit/0b8395ed7088313cd6fe2e7e74ca56340f194431
