### ISSUE TITLE
422 Unprocessable Entity, when sending need help for a drain

### ISSUE THREAD

**Issue by Samweli** [Samweli/twaa-mtaro#67]
@mloweedgar i get this error when sending need help description

Started POST "/need_helps.json"  at 2017-09-11 16:27:26 +0000
Processing by NeedHelpsController#create as JSON
  Parameters: {"commit"=>"Send", "utf8"=>"✓", "need_help"=>{"help_needed"=>"Needs tool", "gid"=>"2146"}, "locale"=>"en"}
Completed 422 Unprocessable Entity in 6.7ms (Views: 2.0ms | ActiveRecord: 0.2ms)

**Comment by Mloweedgar** [comment]
closed in https://github.com/Samweli/twaa-mtaro/commit/bb07202b2c8c32d5d89c19e8b23bc424826255e9
